const state={page:0,perPage:6,answers:[],questions:[]};
const qs=a=>document.querySelector(a);
const qsa=a=>Array.from(document.querySelectorAll(a));
function setProgress(){const total=state.questions.length||0;const filled=state.answers.filter(v=>typeof v==='number').length;const pct=total?Math.round(filled*100/total):0;const el=qs('#progressInner');if(el)el.style.width=pct+'%';const pt=qs('#pageTitle');if(pt){const pages=Math.ceil((total||1)/state.perPage);pt.textContent=`第 ${state.page+1} 页 / 共 ${pages} 页`;}}
function renderPage(p){const start=p*state.perPage;const end=Math.min(start+state.perPage,state.questions.length);const list=qs('#questionsList');if(!list)return;let html='';for(let i=start;i<end;i++){const q=state.questions[i]||{text:''};html+=`<div class="q-item"><div class="q-title">${q.text||''}</div><div class="likert">`;
  for(let s=1;s<=7;s++){const active = state.answers[i]===s ? ' active' : ''; const aria = s===1?'非常不同意': s===2?'轻微不同意': s===3?'略偏不同意': s===4?'中立': s===5?'略偏同意': s===6?'轻微同意':'非常同意';
    html+=`<button data-index="${i}" data-score="${s}" class="dot${active}" aria-label="${aria}"></button>`;
  }
  html+='</div></div>';
}
list.innerHTML=html;const prev=qs('#prevBtn');const next=qs('#nextBtn');if(prev)prev.disabled=p===0;const all=pageAnswered(p);if(next){next.disabled=!all;next.textContent=(end===state.questions.length)?'提交':'下一页';}setProgress();}
function highlightRange(el,score,on){const parent=el&&el.closest('.likert');if(!parent)return;const dots=Array.from(parent.querySelectorAll('.dot'));const min=Math.min(score,4),max=Math.max(score,4);dots.forEach(d=>{const s=parseInt(d.getAttribute('data-score'),10);if(s>=min&&s<=max){d.style.background=on?'#dbe3ff':'';}});}
function bindEvents(){const list=qs('#questionsList');if(!list)return;list.addEventListener('click',e=>{const d=e.target.closest('.dot');if(!d)return;const s=parseInt(d.getAttribute('data-score'),10);const idx=parseInt(d.getAttribute('data-index'),10);state.answers[idx]=s;renderPage(state.page);});list.addEventListener('mouseenter',e=>{const d=e.target.closest('.dot');if(!d)return;const s=parseInt(d.getAttribute('data-score'),10);highlightRange(d,s,true);},true);list.addEventListener('mouseleave',e=>{const d=e.target.closest('.dot');if(!d)return;const s=parseInt(d.getAttribute('data-score'),10);highlightRange(d,s,false);},true);} 
function pageAnswered(p){const start=p*state.perPage;const end=Math.min(start+state.perPage,state.questions.length);for(let i=start;i<end;i++){if(typeof state.answers[i]!== 'number') return false;}return true;}
function nextPage(){if(!pageAnswered(state.page))return;const pages=Math.ceil(state.questions.length/state.perPage);if(state.page<pages-1){state.page++;renderPage(state.page);}else{submitAnswers();}}
function prevPage(){if(state.page>0){state.page--;renderPage(state.page);}}
async function submitAnswers(){try{const res=await fetch('calculate.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers:state.answers})});let type=null;try{const data=await res.json();type=(data&&data.type)||data;}catch(e){type=await res.text();}type=String(type||'').trim().toUpperCase();if(!type)type='UNKNOWN';window.location.href='result.html?type='+encodeURIComponent(type);}catch(e){alert('提交失败，请稍后重试');}}
async function init(){const prev=qs('#prevBtn'),next=qs('#nextBtn');if(prev)prev.addEventListener('click',prevPage);if(next)next.addEventListener('click',nextPage);try{const base=window.location.pathname.includes('huilanweb')?'/huilanweb':'';const url=base+'/data/mbti_questions.json';let payload;try{const res=await fetch(url);if(!res.ok)throw new Error('fetch json failed');payload=await res.json();}catch(_){const alt=await fetch('get_questions.php');payload=await alt.json();}let arr=Array.isArray(payload)?payload:(payload&&payload.data&&Array.isArray(payload.data.questions)?payload.data.questions:[]);state.questions=arr.map(q=>({id:q.id,text:q.text||q.question||'',dimension:q.dimension||''}));state.answers=new Array(state.questions.length);bindEvents();renderPage(0);}catch(e){alert('题库加载失败');state.questions=[];state.answers=[];bindEvents();renderPage(0);}}
document.addEventListener('DOMContentLoaded',init);