const state={current:0,answers:[],questions:[]};
const qs=a=>document.querySelector(a);
const qsa=a=>Array.from(document.querySelectorAll(a));
function setProgress(){const total=state.questions.length||0;const filled=state.answers.filter(v=>typeof v==='number').length;const pct=total?Math.round(filled*100/total):0;const el=qs('#progressInner');if(el)el.style.width=pct+'%';}
function renderQuestion(i){const q=state.questions[i]||{text:''};const t=qs('#questionText');if(t)t.textContent=q.text||'';qsa('#likert .dot').forEach(d=>{d.classList.remove('active');d.style.background='';});const s=state.answers[i];if(typeof s==='number'){const el=qs(`#likert .dot[data-score="${s}"]`);if(el)el.classList.add('active');}const prev=qs('#prevBtn');const next=qs('#nextBtn');if(prev)prev.disabled=i===0;const has=typeof state.answers[i]==='number';if(next){next.disabled=!has;next.textContent=i===state.questions.length-1?'提交':'下一题';}setProgress();}
function highlightRange(score,on){const dots=qsa('#likert .dot');const min=Math.min(score,4),max=Math.max(score,4);dots.forEach(d=>{const s=parseInt(d.getAttribute('data-score'),10);if(s>=min&&s<=max){if(on){d.style.background='#dbe3ff';}else{d.style.background='';}}});const active=qs(`#likert .dot[data-score="${state.answers[state.current]}"]`);if(active)active.style.background='';}
function bindLikert(){qsa('#likert .dot').forEach(d=>{d.addEventListener('click',()=>{const s=parseInt(d.getAttribute('data-score'),10);state.answers[state.current]=s;renderQuestion(state.current);});d.addEventListener('mouseenter',()=>{const s=parseInt(d.getAttribute('data-score'),10);highlightRange(s,true);});d.addEventListener('mouseleave',()=>{const s=parseInt(d.getAttribute('data-score'),10);highlightRange(s,false);});});}
function nextQuestion(){if(typeof state.answers[state.current]!=='number')return;if(state.current<state.questions.length-1){state.current++;renderQuestion(state.current);}else{submitAnswers();}}
function prevQuestion(){if(state.current>0){state.current--;renderQuestion(state.current);}}
async function submitAnswers(){try{const res=await fetch('/mbti/calculate.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers:state.answers})});let type=null;try{const data=await res.json();type=(data&&data.type)||data;}catch(e){type=await res.text();}type=String(type||'').trim().toUpperCase();if(!type)type='UNKNOWN';window.location.href='/mbti/result.html?type='+encodeURIComponent(type);}catch(e){alert('提交失败，请稍后重试');}}
async function init(){const prev=qs('#prevBtn'),next=qs('#nextBtn');if(prev)prev.addEventListener('click',prevQuestion);if(next)next.addEventListener('click',nextQuestion);bindLikert();try{const res=await fetch('/mbti/get_questions.php');const data=await res.json();state.questions=Array.isArray(data)?data:[];state.answers=new Array(state.questions.length);renderQuestion(0);}catch(e){state.questions=[];state.answers=[];renderQuestion(0);}}
document.addEventListener('DOMContentLoaded',init);